// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc3mezvYwWJZowkYI8yVUJyP8_S2l1bkU',
    appId: '1:190611284673:web:54af63b3af737dbe00aa40',
    messagingSenderId: '190611284673',
    projectId: 'booking-ticket-film',
    authDomain: 'booking-ticket-film.firebaseapp.com',
    storageBucket: 'booking-ticket-film.appspot.com',
    measurementId: 'G-8NQG1XF1YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasLSS-WtgWh5OggFU4j4g3zitbCsc0w8',
    appId: '1:190611284673:android:e97bb11ffec4c8e900aa40',
    messagingSenderId: '190611284673',
    projectId: 'booking-ticket-film',
    storageBucket: 'booking-ticket-film.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNPr_SGIBezBd_cfPlfmRgS6plva0OQg',
    appId: '1:190611284673:ios:3d540540f02a1f4100aa40',
    messagingSenderId: '190611284673',
    projectId: 'booking-ticket-film',
    storageBucket: 'booking-ticket-film.appspot.com',
    iosBundleId: 'com.example.bookingTiketFilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCNPr_SGIBezBd_cfPlfmRgS6plva0OQg',
    appId: '1:190611284673:ios:3d540540f02a1f4100aa40',
    messagingSenderId: '190611284673',
    projectId: 'booking-ticket-film',
    storageBucket: 'booking-ticket-film.appspot.com',
    iosBundleId: 'com.example.bookingTiketFilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc3mezvYwWJZowkYI8yVUJyP8_S2l1bkU',
    appId: '1:190611284673:web:e5e4e49d7d1ffd8200aa40',
    messagingSenderId: '190611284673',
    projectId: 'booking-ticket-film',
    authDomain: 'booking-ticket-film.firebaseapp.com',
    storageBucket: 'booking-ticket-film.appspot.com',
    measurementId: 'G-CTEMQFZNNM',
  );
}
